"""
Django settings for survey_rewards_site project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

try:
    import dj_database_url
    HAS_DB_URL = True
except ImportError:
    HAS_DB_URL = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-(dnx4d3-&#-ud#5*-=ocsbam%jfuenef=h8y=d6d4)7$3i73aa')

# SECURITY WARNING: don't run with debug turned on in production!
# TEMPORARILY enabled for debugging on Vercel
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')
if '*' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('*')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Custom apps
    'users',
    'surveys',
    'payments',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'survey_rewards_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'survey_rewards_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# For Vercel, use PostgreSQL (recommended for production)
# SQLite is used for local development
if os.environ.get('DATABASE_URL') and HAS_DB_URL:
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    # On Vercel serverless, use /tmp for SQLite (temporary)
    # For production, set DATABASE_URL environment variable with PostgreSQL
    import sys
    if os.environ.get('VERCEL'):
        # Vercel's serverless environment - use /tmp (data won't persist)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': '/tmp/db.sqlite3',
            }
        }
    else:
        # Local development
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise for static files in production
# Use simpler storage for Vercel serverless
import os
if os.environ.get('VERCEL'):
    STATICFILES_STORAGE = 'whitenoise.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Authentication
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'

# Email Configuration
# For development: Console backend (prints emails to console)
# For production: Use SMTP or service like SendGrid
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Messages
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}

# =====================================================
# Payment Gateway Configuration
# =====================================================

# EasyPaisa Configuration
# Get credentials from: https://www.easypaisa.com.pk/merchant
# Documentation: https://developer.easypaisa.com.pk
EASYPAISA_CONFIG = {
    'store_id': os.environ.get('EASYPAISA_STORE_ID', 'YOUR_EASYPAISA_STORE_ID'),
    'password': os.environ.get('EASYPAISA_PASSWORD', 'YOUR_EASYPAISA_PASSWORD'),
    'is_production': os.environ.get('EASYPAISA_IS_PRODUCTION', 'False') == 'True',
}

# JazzCash Configuration
# Get credentials from: https://www.jazzcash.com.pk/merchant
JAZZCASH_CONFIG = {
    'merchant_id': os.environ.get('JAZZCASH_MERCHANT_ID', 'YOUR_JAZZCASH_MERCHANT_ID'),
    'password': os.environ.get('JAZZCASH_PASSWORD', 'YOUR_JAZZCASH_PASSWORD'),
    'hash_key': os.environ.get('JAZZCASH_HASH_KEY', 'YOUR_JAZZCASH_HASH_KEY'),
    'is_production': os.environ.get('JAZZCASH_IS_PRODUCTION', 'False') == 'True',
}

# PayPal Configuration
# Get credentials from: https://developer.paypal.com/
PAYPAL_CONFIG = {
    'client_id': os.environ.get('PAYPAL_CLIENT_ID', 'YOUR_PAYPAL_CLIENT_ID'),
    'client_secret': os.environ.get('PAYPAL_CLIENT_SECRET', 'YOUR_PAYPAL_CLIENT_SECRET'),
    'is_production': os.environ.get('PAYPAL_IS_PRODUCTION', 'False') == 'True',
}
