# Generated by Django 5.2.4 on 2026-04-11 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('health', 'Health & Wellness'), ('tech', 'Technology'), ('shopping', 'Shopping'), ('finance', 'Finance'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('food', 'Food & Dining'), ('travel', 'Travel'), ('general', 'General')], default='general', max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy (2-5 mins)'), ('medium', 'Medium (5-10 mins)'), ('hard', 'Hard (10-20 mins)')], default='easy', max_length=20)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_time', models.IntegerField(help_text='Estimated time in minutes')),
                ('questions_count', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('current_participants', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('text', 'Text Answer'), ('rating', 'Rating (1-5)'), ('yes_no', 'Yes/No')], default='multiple_choice', max_length=50)),
                ('options', models.JSONField(blank=True, help_text='For multiple choice questions', null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_data', models.JSONField(help_text='Store answers as JSON')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('reward_earned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.survey')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
